name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have read the [Contributing Guidelines](../../CONTRIBUTING.md)
          required: true
        - label: I am using the latest version of the application
          required: false

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL/Fedora)
        - Linux (Arch)
        - Linux (Other)
        - Windows 10
        - Windows 11
        - Windows Server
        - macOS
        - Other
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: System Architecture
      description: What system architecture are you using?
      options:
        - x86_64 (AMD64)
        - ARM64
        - ARM32
        - Other
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: Application Version
      description: What version of cf-ddns-updater are you using?
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version (if building from source)
      description: What version of Go are you using? (run `go version`)
      placeholder: "go version go1.23.0 linux/amd64"
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share your configuration (remove sensitive information like API tokens)
      placeholder: |
        {
          "cloudflare": {
            "api_token": "[REDACTED]",
            "zone_id": "[REDACTED]"
          },
          "domains": [
            {
              "name": "example.com",
              "type": "A"
            }
          ],
          "interval": 300
        }
      render: json
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Please provide relevant log output (remove sensitive information)
      placeholder: Paste log output here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Any error messages you're seeing
      placeholder: Paste error messages here...
      render: shell
    validations:
      required: false

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install cf-ddns-updater?
      options:
        - Downloaded binary from GitHub releases
        - Built from source
        - Used install script
        - Package manager
        - Docker/Container
        - Other
    validations:
      required: true

  - type: dropdown
    id: deployment-method
    attributes:
      label: Deployment Method
      description: How are you running cf-ddns-updater?
      options:
        - Systemd service
        - Manual execution
        - Cron job
        - Docker container
        - Windows service
        - Other
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Network configuration details
        - Firewall settings
        - Recent changes to system
        - Screenshots (if applicable)
        - Related issues or discussions
    validations:
      required: false

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Steps Attempted
      description: What troubleshooting steps have you already tried?
      options:
        - label: Restarted the application
        - label: Checked configuration file syntax
        - label: Verified Cloudflare API token permissions
        - label: Tested network connectivity
        - label: Checked system logs
        - label: Tried with a minimal configuration
        - label: Updated to the latest version

  - type: markdown
    attributes:
      value: |
        ---
        
        ### 🔒 Security Note
        
        **Never include sensitive information** such as:
        - API tokens or keys
        - Passwords
        - Personal domain names (if privacy is a concern)
        - IP addresses (if privacy is a concern)
        
        If you need to share sensitive information, please use a [GitHub Security Advisory](../security/advisories/new) instead.
        
        ### 📞 Need Help?
        
        - Check our [documentation](../../README.md)
        - Browse [existing issues](../issues)
        - Join [GitHub Discussions](../discussions)
        
        Thank you for helping improve cf-ddns-updater! 🎉